workspace:
  base: /test
  path: content-layer-demo

services:
  web:
    image: fpfis/httpd-php-dev:7.1
    environment:
      - DOCUMENT_ROOT=/test/content-layer-demo
  mysql:
    image: percona/percona-server:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  selenium:
    image: selenium/standalone-chrome:3.11
    environment:
      - DISPLAY=:99
      - SE_OPTS=-debug
  authentication:
    image: openeuropa/pcas-server:latest

pipeline:
  composer-install:
    group: prepare
    image: fpfis/httpd-php-dev:7.1
    volumes:
      - /cache:/cache
    commands:
      - composer install

  build-site-rtd:
    group: build-site
    image: fpfis/httpd-php-dev:7.1
    volumes:
    - /cache:/cache
    commands:
    - composer --working-dir=site-rtd install

  build-site-agri:
    group: build-site
    image: fpfis/httpd-php-dev:7.1
    volumes:
    - /cache:/cache
    commands:
    - composer --working-dir=site-agri install

  build-site-energy:
    group: build-site
    image: fpfis/httpd-php-dev:7.1
    volumes:
    - /cache:/cache
    commands:
    - composer --working-dir=site-energy install

  install-site-rtd:
    group: install-site
    image: fpfis/httpd-php-dev:7.1
    commands:
      - ./vendor/bin/run --working-dir='/test/content-layer-demo/site-rtd' drupal:site-install

  install-site-agri:
    group: install-site
    image: fpfis/httpd-php-dev:7.1
    commands:
      - ./vendor/bin/run --working-dir='/test/content-layer-demo/site-agri' drupal:site-install

  install-site-energy:
    group: install-site
    image: fpfis/httpd-php-dev:7.1
    commands:
      - ./vendor/bin/run --working-dir='/test/content-layer-demo/site-energy' drupal:site-install

  grumphp:
    group: test
    image: fpfis/httpd-php-dev:7.1
    commands:
      - ./vendor/bin/grumphp run

  behat:
    group: test
    image: fpfis/httpd-php-dev:7.1
    commands:
      - ./vendor/bin/behat

  start-demo:
    group: test
    image: fpfis/drone-frpc-plugin:latest
    secrets: [ frpc_token, frpc_server ]
    endpoint: web:8080
    gen_auth: yes
    domain: ${DRONE_REPO_NAME}-${DRONE_BUILD_NUMBER}-demo.ci.fpfis.tech.ec.europa.eu
    url_output_file: /test/.frpc
    when:
      event: push
      branch: [ demo-*, debug-* ]
      status: [ success, failure ]
