workspace:
  base: /test
  path: europa-demo

services:
  web:
    image: fpfis/php71-dev
    environment:
      - DOCUMENT_ROOT=/test/europa-demo
  mysql:
    image: percona/percona-server:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  selenium:
    image: selenium/standalone-chrome:3.11
    environment:
      - DISPLAY=:99
      - SE_OPTS=-debug

pipeline:
  composer-install:
    group: prepare
    image: fpfis/php71-build
    volumes:
      - /cache:/cache
    commands:
      - composer install

  site-install:
    image: fpfis/php71-build
    commands:
      - ./vendor/bin/run drupal:site-install
      # Reset permission since installation runs as root. @todo Fix this.
      - chown -R 1000:1000 build/sites/default
      - chmod -R 777 /tmp

  start-demo:
    image: fpfis/drone-frpc-plugin:latest
    secrets: [ frpc_token, frpc_server ]
    endpoint: web:8080
    gen_auth: yes
    domain: ${DRONE_REPO_NAME}-${DRONE_BUILD_NUMBER}-demo.ci.fpfis.tech.ec.europa.eu
    url_output_file: /test/.frpc
    when:
      event: push
      branch: [ demo-*, debug-* ]
      status: [ success, failure ]

  grumphp:
    group: test
    image: fpfis/php71-build
    commands:
      - ./vendor/bin/grumphp run

  behat:
    group: test
    image: fpfis/php71-build
    commands:
      - ./vendor/bin/behat
