workspace:
  base: /test
  path: content-layer-demo

services:
  web:
    image: fpfis/httpd-php-dev:7.1
    environment:
      - DOCUMENT_ROOT=/test/content-layer-demo
  mysql:
    image: percona/percona-server:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  selenium:
    image: selenium/standalone-chrome:3.11
    environment:
      - DISPLAY=:99
      - SE_OPTS=-debug
  authentication:
    image: openeuropa/pcas-server:latest
  sparql:
    image: openeuropa/triple-store-dev
    environment:
      - SPARQL_UPDATE=true
      - DBA_PASSWORD=dba

pipeline:
  composer-install:
    group: prepare
    image: fpfis/httpd-php-dev:7.1
    volumes:
      - /cache:/cache
    commands:
      - composer install

  build-site-info:
    group: build-site
    image: fpfis/httpd-php-dev:7.1
    volumes:
      - /cache:/cache
    commands:
      - composer --working-dir=sites/info install

  build-site-inea:
    group: build-site
    image: fpfis/httpd-php-dev:7.1
    volumes:
      - /cache:/cache
    commands:
      - composer --working-dir=sites/inea install

  build-site-energy:
    group: build-site
    image: fpfis/httpd-php-dev:7.1
    volumes:
      - /cache:/cache
    commands:
      - composer --working-dir=sites/energy install

  install-site-info:
    group: install-site
    image: fpfis/httpd-php-dev:7.1
    commands:
      - ./vendor/bin/run --working-dir='/test/content-layer-demo/sites/info' drupal:site-install

  install-site-inea:
    group: install-site
    image: fpfis/httpd-php-dev:7.1
    commands:
      - ./vendor/bin/run --working-dir='/test/content-layer-demo/sites/inea' drupal:site-install

  install-site-energy:
    group: install-site
    image: fpfis/httpd-php-dev:7.1
    commands:
      - ./vendor/bin/run --working-dir='/test/content-layer-demo/sites/energy' drupal:site-install

  grumphp:
    group: test
    image: fpfis/httpd-php-dev:7.1
    commands:
      - ./vendor/bin/grumphp run

  behat-general:
    group: test
    image: fpfis/httpd-php-dev:7.1
    commands:
      - ./vendor/bin/behat

  behat-inea:
    group: test
    image: fpfis/httpd-php-dev:7.1
    commands:
      - ./vendor/bin/behat -p inea

  behat-energy:
    group: test
    image: fpfis/httpd-php-dev:7.1
    commands:
      - ./vendor/bin/behat -p energy

  behat-info:
    group: test
    image: fpfis/httpd-php-dev:7.1
    commands:
      - ./vendor/bin/behat -p info

  start-demo:
    group: test
    image: fpfis/drone-frpc-plugin:latest
    secrets: [ frpc_token, frpc_server ]
    endpoint: web:8080
    gen_auth: yes
    domain: ${DRONE_REPO_NAME}-${DRONE_BUILD_NUMBER}-demo.ci.fpfis.tech.ec.europa.eu
    url_output_file: /test/.frpc
    when:
      event: push
      branch: [ demo-*, debug-* ]
      status: [ success, failure ]
