<?php

/**
 * @file
 * Contains code and hook implementation for the Europa demo core module.
 */

declare(strict_types = 1);

use Drupal\Component\Utility\Html;
use Drupal\Core\Url;
use Drupal\europa_demo_core\EuropaDemoRdfListBuilder;
use Drupal\ui_patterns\Element\PatternContext;

/**
 * Implements hook_theme().
 */
function europa_demo_core_theme($existing, $type, $theme, $path): array {
  return [
    'europa_demo_footer_corporate_top' => [
      'render element' => 'element',
    ],
    'europa_demo_footer_corporate_bottom' => [
      'render element' => 'element',
    ],
    'europa_demo_search' => [
      'render element' => 'element',
    ],
    'europa_demo_site_banner' => [
      'variables' => [
        'title' => NULL,
        'uri' => NULL,
        'background' => NULL,
      ],
    ],
    'europa_demo_site_ribbon' => [
      'variables' => [
        'name' => NULL,
      ],
    ],
  ];
}

/**
 * Prepares variables for the site banner template.
 *
 * Default template: europa-demo-site-banner.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - link_title: The text to be used for the link.
 *   - link: The location where the link should point to.
 *   - background: A path to an image to use as background.
 */
function template_preprocess_europa_demo_site_banner(array &$variables): void {
  global $base_root, $base_path;

  $variables['link'] = [
    '#type' => 'link',
    '#url' => Url::fromUri($variables['uri']),
    '#title' => $variables['title'],
  ];

  $variables['background'] = $base_root . $base_path . Html::escape($variables['background']);
}

/**
 * Implements hook_ui_patterns_theme_suggestions_alter().
 */
function europa_demo_core_ui_patterns_suggestions_alter(array &$suggestions, array $variables, PatternContext $context): void {

  // Provide suggestions for patterns with context type set to "entity_list".
  // This hooks assumes that contexts will provide "entity_type" and "bundle"
  // properties. Also, the actual list of entities must be provided in a
  // "entities" context property.
  if ($context->isOfType('entity_list')) {
    $hook = $variables['theme_hook_original'];

    /** @var \Drupal\Core\Entity\ContentEntityBase $entity */
    $entity_type = $context->getProperty('entity_type');
    $bundle = $context->getProperty('bundle');

    $suggestions[] = $hook . '__entity_list';
    $suggestions[] = $hook . '__entity_list__' . $entity_type;
    $suggestions[] = $hook . '__entity_list__' . $entity_type . '__' . $bundle;
  }
}

/**
 * Implements hook_entity_type_alter().
 *
 * Overriding the default RDF entity list builder handler with our own.
 */
function europa_demo_core_entity_type_alter(array &$entity_types): void {
  if (!isset($entity_types['rdf_entity'])) {
    return;
  }

  /** @var \Drupal\Core\Entity\ContentEntityTypeInterface $rdf */
  $rdf = $entity_types['rdf_entity'];
  $rdf->setHandlerClass('list_builder', EuropaDemoRdfListBuilder::class);
}
